//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef4
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string id { get; set; }
        public string empname { get; set; }
        public string designation { get; set; }
        public string phone { get; set; }
        public string PId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
