//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EfCoreEntities1 : DbContext
    {
        public EfCoreEntities1()
            : base("name=EfCoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
    
        public virtual ObjectResult<Person> selectinto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Person>("selectinto");
        }
    
        public virtual ObjectResult<Person> selectinto(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Person>("selectinto", mergeOption);
        }
    }
}
